<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Admin Area</title>
        <meta name="description" content="website description" />
        <meta name="keywords" content="website keywords, website keywords" />

        <? /* <link rel="stylesheet" type="text/css" href="/css/<?=$this->theme?>/style.css" title="style" /> */ ?>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script src="/js/bootstrap.min.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" title="style" />

        <style>
            body {
                padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
            }
        </style>
    </head>

    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="/admin">Admin Area</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <?php 
                                $pages = $this->navigation()->findAllBy('module', 'admin');
                                foreach ($pages as $page) :
                            ?>
                                <li <?php if($page->isActive()):?>class="active"<?php endif;?>>
                                    <?php
                                        $href = '/' . $page->module . '/' . $page->controller;
                                        if ($page->params) {
                                            $href .= '/?type=' . $page->params['type'];
                                        } 
                                    ?>
                                    <a href="<?php echo $href;?>"><?php echo $page->label;?></a>
                                </li>
                            <?php endforeach;?>
                        </ul>
                    </div><!--/.nav-collapse -->
                    <div class="pull-right">
                        <?php if ($this->currentUser): ?>
                            <a href='/user/auth/logout'>Logout</a>
                        <?php else: ?>
                            <?php //echo $this->action('index', 'auth', 'user') ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->layout()->render('_common/messages/default', array('messages' => $this->layout()->messages)); ?>

            <?php
            $activePage = $this->navigation()->findOneBy('active', true);
            if ($activePage):
                $label = $activePage->get('label');
                ?>
                <?php echo $this->navigation()->breadcrumbs()->setPartial('_common/breadcrumbs/default.phtml')->setLinkLast(false)->render(); ?>
                <div class="page-header">
                    <h1><?php echo $label ?></h1>
                </div>
            <?php endif; ?>
            <!-- insert the page content here -->
            <?php echo $this->layout()->content ?>

        </div>       

    </body>
</html>
