<form class="form-horizontal" enctype="multipart/form-data" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>" name="<?= $this->form->getName() ?>">
    <?php foreach ($this->form->getElements() as $element): ?>
        <?php
        $errors = $element->getMessages();
        ?>

        <?php if ($element instanceof Zend_Form_Element_Submit): ?>
            <?php $element->setAttrib('class', 'btn btn-primary') ?>
            <?php echo $element ?>
        <?php elseif ($element instanceof Zend_Form_Element_Hidden): ?>
            <?php echo $element ?>
        <?php else: ?>

            <div class="form-group">
                <?php if ($element->getAttrib('showLabel') !== false): ?>
                    <?php
                    if ($element->isRequired()) {
                        //echo ' *';
                        $element->setLabel($element->getLabel() . ' *');
                    }
                    echo $this->formLabel($element->getName(), $element->getLabel(), array('class' => 'col-sm-2 control-label', 'style' => ''));

                    /* $tooltip = $element->getDecorator('Tooltip');
                      if ($tooltip) {
                      $tooltip->setElement($element);
                      echo $tooltip->render('');
                      $element->removeDecorator('Tooltip');
                      } */
                    ?> 
                <?php endif; ?>

                <div class="col-sm-4">                        
                    <?php
                    $element->setAttrib('class', 'form-control');
                    echo $element;
                    ?>     
                </div>
                <?php if (count($errors)): ?>
                    <span class="col-sm-4 help-inline">
                        <?php foreach ($errors as $message): ?>
                            <?php echo $message ?><br/>
                        <?php endforeach; ?>
                    </span>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</form>