<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Acl
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Acl extends EntityRepository
{
    
    public function truncate()
    {
        $this->getEntityManager()
                ->getConnection()
                ->executeQuery('truncate '.$this->getClassMetadata()->getTableName());
    }
}
