<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Acl
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Users extends EntityRepository {

    public function getUserByEmail($emailAddress) {
        return $this->findBy(array('userEmail' => $emailAddress));
    }

}
