<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Acl
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Users extends EntityRepository {

    /**
     * 
     * @param string $emailAddress
     * @return Model\Entities\User
     */
    public function getUserByEmail($emailAddress) {
        return $this->findOneBy(array('userEmail' => $emailAddress));
    }

    /**
     * 
     * @param string $code
     * @return Model\Entities\User
     */
    public function getUserByPassCode($code){
        return $this->findOneBy(array('userResetPassCode' => $code));
    }
    
    /**
     * 
     * @param string $code
     * @return Model\Entities\User
     */    
    public function getUserByActivationCode($code){
        return $this->findOneBy(array('userActivationCode' => $code));
    }    
}
